import csv
import random as r
from datetime import datetime
import datetime as dt
import json

r.seed(datetime.now().timestamp())

arrayCognomi = [
    "Rossi",
    "Russo",
    "Ferrari",
    "Esposito",
    "Bianchi",
    "Romano",
    "Colombo",
    "Bruno",
    "Ricci",
    "Marino",
    "Costa",
    "Franco",
    "Gallo",
    "Conti",
    "Greco",
    "Martino",
    "Giordano",
    "Rizzo",
    "Mancini",
    "Villa",
    "Mauro",
    "Lombardi",
    "Fontana",
    "Roberto",
    "Barbieri",
    "Moretti",
    "Bianco",
    "Martini",
    "Fratelli",
    "Mariani",
    "Rinaldi",
    "Amato",
    "Galli",
    "Ferrara",
    "Caruso",
    "Leone",
    "Mario",
    "Santoro",
    "Longo",
    "Conte",
    "Sala",
    "Martinelli",
    "Serra",
    "Angelo",
    "Dalla",
    "Marchetti",
    "Marini",
    "Salvatore",
    "Fabbri",
    "Fiore",
    "Ferri",
    "Gentile",
    "Gatti",
    "Palma",
    "Monti",
    "Soc",
    "Vitale",
    "Lombardo",
    "Luca",
    "Bernardi",
    "Pellegrini",
    "Messina",
    "Benedetti",
    "Massimo",
    "Coppola",
    "Morelli",
    "Grassi",
    "Testa",
    "Marchi",
    "Parisi",
    "Ferraro",
    "Michele",
    "Santis",
    "Rocca",
    "Valentini",
    "Riva",
    "Agostino",
    "Angelis",
    "Palumbo",
    "Pasquale",
    "Giorgi",
    "Farina",
    "Silvestri",
    "Sanna",
    "Rizzi",
    "Cattaneo",
    "Poli",
    "Mazza",
    "Paola",
    "Lombardi",
    "Pellegrino",
    "Piazza",
    "Leo",
    "Orlando",
    "Carbone",
    "Re",
    "Moro",
    "Neri",
    "Giuliani",
    "Guerra",
]

arrayNomi = [
    "Alessandro",
    "Andrea",
    "Antonio",
    "Alessio",
    "Alberto",
    "Angelo",
    "Amedeo",
    "Arturo",
    "Augusto",
    "Alfredo",
    "Beatrice",
    "Bianca",
    "Benedetta",
    "Barbara",
    "Bettina",
    "Biancamaria",
    "Bruna",
    "Bianca Maria",
    "Biancamaria",
    "Carlo",
    "Claudio",
    "Cristian",
    "Cristina",
    "Chiara",
    "Cecilia",
    "Cinzia",
    "Carmelo",
    "Cesare",
    "Caterina",
    "Daniele",
    "Davide",
    "Diego",
    "Dario",
    "Domenico",
    "Dora",
    "Deborah",
    "Daniela",
    "Donatella",
    "Diana",
    "Emanuele",
    "Enrico",
    "Edoardo",
    "Elena",
    "Elisa",
    "Eleonora",
    "Emanuela",
    "Emma",
    "Erica",
    "Enza",
    "Fabio",
    "Francesco",
    "Federico",
    "Federica",
    "Filippo",
    "Flavio",
    "Fiorella",
    "Fulvio",
    "Franco",
    "Federica",
    "Gabriele",
    "Giorgio",
    "Giacomo",
    "Giovanni",
    "Giuseppe",
    "Giulia",
    "Greta",
    "Gloria",
    "Giovanna",
    "Graziella",
    "Hector",
    "Humberto",
    "Horacio",
    "Hugo",
    "Hernán",
    "Héctor",
    "Hugo",
    "Humberto",
    "Horacio",
    "Hernán",
    "Ilaria",
    "Irene",
    "Ivana",
    "Isabella",
    "Isotta",
    "Igor",
    "Ignazio",
    "Isidoro",
    "Ippolito",
    "Italo",
    "Jacopo",
    "Jader",
    "Julio",
    "Javier",
    "Joaquín",
    "Juan",
    "José",
    "Jorge",
    "Julián",
    "Javier",
    "Luca",
    "Lorenzo",
    "Leonardo",
    "Ludovica",
    "Laura",
    "Luisa",
    "Linda",
    "Livia",
    "Luciana",
    "Letizia",
    "Marco",
    "Matteo",
    "Michele",
    "Mirko",
    "Massimo",
    "Manuela",
    "Martina",
    "Monica",
    "Marina",
    "Marianna",
    "Nicola",
    "Nicolò",
    "Nicoletta",
    "Noemi",
    "Natalia",
    "Nunzia",
    "Natalina",
    "Nevio",
    "Nadia",
    "Nico",
    "Olivia",
    "Ornella",
    "Oscar",
    "Omar",
    "Osvaldo",
    "Oreste",
    "Olimpia",
    "Oriana",
    "Olga",
    "Orietta",
    "Paolo",
    "Pietro",
    "Piero",
    "Patrizia",
    "Pamela",
    "Paola",
    "Priscilla",
    "Piera",
    "Pia",
    "Patrizio",
    "Quirino",
    "Quinto",
    "Quintino",
    "Quirico",
    "Quinto",
    "Quintilio",
    "Quirico",
    "Quarto",
    "Quirino",
    "Quinziano",
    "Raffaele",
    "Roberto",
    "Riccardo",
    "Renato",
    "Rocco",
    "Rita",
    "Rosanna",
    "Rosa",
    "Ruggero",
    "Sergio",
    "Simone",
    "Stefano",
    "Samuele",
    "Salvatore",
    "Silvia",
    "Sara",
    "Serena",
    "Susanna",
    "Sabrina",
    "Tiziano",
    "Tommaso",
    "Teresa",
    "Tiziana",
    "Tullio",
    "Tania",
    "Tina",
    "Tania",
    "Tatiana",
    "Tosca",
    "Ugo",
    "Umberto",
    "Ulderico",
    "Uberto",
    "Ubaldo",
    "Ursula",
    "Umberta",
    "Ulrica",
    "Umbertina",
    "Urbano",
    "Valerio",
    "Vincenzo",
    "Valentina",
    "Virginia",
    "Vittorio",
    "Valeria",
    "Vera",
    "Viola",
    "Violetta",
    "Vanda",
    "Walter",
    "Wanda",
    "Xavier",
    "Ximena",
    "Yuri",
    "Yara",
    "Zeno",
    "Zaccaria",
    "Zefiro",
    "Zeno",
    "Zitta",
    "Zaira",
    "Zora",
    "Zaira",
    "Zeta",
]

numeri_telefono = []

while len(numeri_telefono) < 200:
    numero = "+39 " + str(r.randint(3000000000, 3999999999))
    if numero not in numeri_telefono:
        numeri_telefono.append(numero)

# sedi

regioni = {
    "Abruzzo": {
        "provincie": ["L'Aquila", "Teramo", "Pescara", "Chieti"],
        "cap": ["67100", "64100", "65100", "66100"],
    },
    "Basilicata": {
        "provincie": ["Potenza", "Matera", "Matera"],
        "cap": ["85100", "75100", "75100"],
    },
    "Calabria": {
        "provincie": [
            "Cosenza",
            "Catanzaro",
            "Reggio Calabria",
            "Crotone",
            "Vibo Valentia",
        ],
        "cap": ["87100", "88100", "89100", "88900", "89900"],
    },
    "Campania": {
        "provincie": ["Napoli", "Salerno", "Avellino", "Benevento", "Caserta"],
        "cap": ["80100", "84100", "83100", "82100", "81100"],
    },
    "Emilia-Romagna": {
        "provincie": [
            "Bologna",
            "Ferrara",
            "Forlì-Cesena",
            "Modena",
            "Parma",
            "Piacenza",
            "Ravenna",
            "Reggio Emilia",
            "Rimini",
        ],
        "cap": [
            "40100",
            "44100",
            "47100",
            "41100",
            "43100",
            "29100",
            "48100",
            "42100",
            "47900",
        ],
    },
    "Friuli-Venezia Giulia": {
        "provincie": ["Trieste", "Gorizia", "Pordenone", "Udine"],
        "cap": ["34100", "34170", "33170", "33100"],
    },
    "Lazio": {
        "provincie": ["Roma", "Latina", "Frosinone", "Viterbo", "Rieti"],
        "cap": ["00100", "04100", "03100", "01100", "02100"],
    },
    "Liguria": {
        "provincie": ["Genova", "Imperia", "La Spezia", "Savona"],
        "cap": ["16100", "18100", "19100", "17100"],
    },
    "Lombardia": {
        "provincie": [
            "Milano",
            "Bergamo",
            "Brescia",
            "Como",
            "Cremona",
            "Lecco",
            "Lodi",
            "Mantova",
            "Monza e della Brianza",
            "Pavia",
            "Sondrio",
            "Varese",
        ],
        "cap": [
            "20100",
            "24100",
            "25100",
            "22100",
            "26100",
            "23900",
            "26900",
            "46100",
            "20900",
            "27100",
            "23100",
            "21100",
        ],
    },
    "Marche": {
        "provincie": [
            "Ancona",
            "Pesaro e Urbino",
            "Macerata",
            "Ascoli Piceno",
            "Fermo",
        ],
        "cap": ["60100", "61100", "62100", "63100", "63900"],
    },
    "Molise": {
        "provincie": ["Campobasso", "Campobasso", "Isernia"],
        "cap": ["86100", "86100", "86170"],
    },
    "Piemonte": {
        "provincie": [
            "Torino",
            "Alessandria",
            "Asti",
            "Biella",
            "Cuneo",
            "Novara",
            "Vercelli",
        ],
        "cap": ["10100", "15100", "14100", "13900", "12100", "28100", "13100"],
    },
    "Puglia": {
        "provincie": ["Bari", "Brindisi", "Foggia", "Lecce", "Taranto"],
        "cap": ["70100", "72100", "71100", "73100", "74100"],
    },
    "Sardegna": {
        "provincie": ["Cagliari", "Nuoro", "Oristano", "Sassari", "Sud Sardegna"],
        "cap": ["09100", "08100", "09170", "07100", "09010"],
    },
    "Sicilia": {
        "provincie": [
            "Palermo",
            "Agrigento",
            "Caltanissetta",
            "Catania",
            "Enna",
            "Messina",
            "Ragusa",
            "Siracusa",
            "Trapani",
        ],
        "cap": [
            "90100",
            "92100",
            "93100",
            "95100",
            "94100",
            "98100",
            "97100",
            "96100",
            "91100",
        ],
    },
    "Toscana": {
        "provincie": [
            "Firenze",
            "Arezzo",
            "Grosseto",
            "Livorno",
            "Lucca",
            "Massa-Carrara",
            "Pisa",
            "Pistoia",
            "Prato",
            "Siena",
        ],
        "cap": [
            "50100",
            "52100",
            "58100",
            "57100",
            "55100",
            "54100",
            "56100",
            "51100",
            "59100",
            "53100",
        ],
    },
    "Trentino-Alto Adige": {
        "provincie": ["Trento", "Trento", "Bolzano"],
        "cap": ["38100", "38100", "39100"],
    },
    "Umbria": {
        "provincie": ["Perugia", "Perugia", "Terni"],
        "cap": ["06100", "06100", "05100"],
    },
    "Valle d'Aosta": {
        "provincie": ["Aosta", "Aosta", "Aosta"],
        "cap": ["11100", "11100", "11100"],
    },
    "Veneto": {
        "provincie": [
            "Venezia",
            "Belluno",
            "Padova",
            "Rovigo",
            "Treviso",
            "Verona",
            "Vicenza",
        ],
        "cap": ["30100", "32100", "35100", "45010", "31100", "37100", "36100"],
    },
}

indirizzi = [
    "Via Roma 1",
    "Via Verdi 2",
    "Via Garibaldi 3",
    "Via Mazzini 4",
    "Via Leonardo da Vinci 5",
    "Via Manzoni 35",
    "Via Montegrappa 3",
    "Via Marconi 67",
    "Via Volta 43",
    "Via Alessandro Volta 10",
    "Via Galileo Galilei 11",
    "Via Vespucci 12",
    "Via Columbus 18",
    "Via Magellan 14",
    "Via Copernico 15",
    "Via Fermi 16",
    "Via Einstein 12",
    "Via Newton 18",
    "Via Kepler 52",
    "Via Archimede 20",
    "Via Dante Alighieri 21",
    "Via Petrarca 22",
    "Via Boccaccio 23",
    "Via Machiavelli 24",
    "Via Leopardi 25",
    "Via Manzoni 78",
    "Via Montale 27",
    "Via Pascoli 28",
    "Via Carducci 29",
    "Via Annunzio 67",
    "Via Pirandello 31",
    "Via Verga 32",
    "Via De Gasperi 33",
    "Via Kennedy 34",
    "Via Roosevelt 92",
    "Via Churchill 36",
    "Via Stalin 81",
    "Via Lenin 38",
    "Via Gandhi 39",
    "Via Mandela 42",
    "Via Bach 41",
    "Via Beethoven 42",
    "Via Mozart 7",
    "Via Chopin 44",
    "Via Verdi 5",
    "Via Rossini 46",
    "Via Wagner 47",
    "Via Puccini 48",
    "Via Vivaldi 49",
    "Via Bach 50",
    "Via Beethoven 51",
    "Via Mozart 26",
    "Via Chopin 53",
    "Via Verdi 54",
    "Via Rossini 4",
    "Via Wagner 84",
    "Via Puccini 57",
    "Via Vivaldi 59",
    "Via Picasso 59",
    "Via Van Gogh 74",
    "Via Monet 61",
    "Via Renoir 62",
    "Via Degas 63",
    "Via Cézanne 87",
    "Via Gauguin 65",
    "Via Matisse 66",
    "Via Miró 67",
    "Via Kandinsky 28",
    "Via Pollock 69",
    "Via Warhol 70",
    "Via Botticelli 16",
    "Via Raffaello 72",
    "Via Michelangelo 38",
    "Via Caravaggio 74",
    "Via Tiziano 75",
    "Via Leonardo da Vinci 76",
    "Via Giotto 77",
    "Via Donatello 78",
    "Via Brunelleschi 1",
    "Via Bernini 2",
]

# capoluoghi = []
# for regione, info in regioni.items():
#     capoluoghi.append([info["cap"][0], info["provincie"][0], regione])

# crs = []
# for i in range(0, 20):
#     crs.append(
#         [
#             i + 1,
#             "crs" + str(i + 1) + "@gmail.com",
#             numeri_telefono[i],
#             "CRS",
#             indirizzi[i],
#             capoluoghi[i][0],
#             capoluoghi[i][1],
#             capoluoghi[i][2],
#         ]
#     )
# print(crs)

# secondeProvincie = []
# for regione, info in regioni.items():
#     secondeProvincie.append([info["cap"][1], info["provincie"][1], regione])

# so = []
# for i in range(0, 20):
#     so.append(
#         [
#             i + 21,
#             "so" + str(i + 21) + "@gmail.com",
#             numeri_telefono[i + 20],
#             "SO",
#             indirizzi[i + 20],
#             secondeProvincie[i][0],
#             secondeProvincie[i][1],
#             secondeProvincie[i][2],
#         ]
#     )
# print(so)

# terzeProvincie = []
# for regione, info in regioni.items():
#     terzeProvincie.append([info["cap"][2], info["provincie"][2], regione])

# pcr = []
# for i in range(0, 20):
#     pcr.append(
#         [
#             i + 41,
#             "pcr" + str(i + 41) + "@gmail.com",
#             numeri_telefono[i + 40],
#             "PCR",
#             indirizzi[i + 40],
#             terzeProvincie[i][0],
#             terzeProvincie[i][1],
#             terzeProvincie[i][2],
#         ]
#     )
# print(pcr)

# METTERE ID SEDE
# ops = [
#     [
#         1,
#         "Alessandra",
#         "Lorenzi",
#         "alessandra.lorenzi@gmail.com",
#         "+390609577324",
#         "Trasportatore",
#     ],
#     [
#         2,
#         "Aurelio",
#         "Peano",
#         "aurelio.peano@gmail.com",
#         "+397008451872",
#         "Trasportatore",
#     ],
#     [3, "Silvia", "Crotta", "silvia.crotta@gmail.com", "+393414395310", "Magazziniere"],
#     [4, "Lucio", "Testa", "lucio.testa@gmail.com", "+398184532667", "Magazziniere"],
#     [
#         5,
#         "Salvatore",
#         "Scarpa",
#         "salvatore.scarpa@gmail.com",
#         "+392261206459",
#         "Magazziniere",
#     ],
#     [
#         6,
#         "Renato",
#         "Lombardi",
#         "renato.lombardi@gmail.com",
#         "+391869894377",
#         "Trasportatore",
#     ],
#     [
#         7,
#         "Giacomo",
#         "Ferrara",
#         "giacomo.ferrara@gmail.com",
#         "+395810154858",
#         "Trasportatore",
#     ],
#     [
#         8,
#         "Serena",
#         "Crespi",
#         "serena.crespi@gmail.com",
#         "+397784711729",
#         "Trasportatore",
#     ],
#     [
#         9,
#         "Anna",
#         "De Carlo",
#         "anna.de carlo@gmail.com",
#         "+391451764342",
#         "Trasportatore",
#     ],
#     [
#         10,
#         "Patrizia",
#         "Scarpa",
#         "patrizia.scarpa@gmail.com",
#         "+397570368242",
#         "Magazziniere",
#     ],
#     [11, "Bastiano", "Zen", "bastiano.zen@gmail.com", "+395333122280", "Trasportatore"],
#     [
#         12,
#         "Bartolomeo",
#         "Astolfi",
#         "bartolomeo.astolfi@gmail.com",
#         "+396808747170",
#         "Trasportatore",
#     ],
#     [
#         13,
#         "Piero",
#         "Ghisalberti",
#         "piero.ghisalberti@gmail.com",
#         "+391151068465",
#         "Trasportatore",
#     ],
#     [
#         14,
#         "Vincenzo",
#         "Russo",
#         "vincenzo.russo@gmail.com",
#         "+390386049319",
#         "Trasportatore",
#     ],
#     [
#         15,
#         "Cesare",
#         "Mancini",
#         "cesare.mancini@gmail.com",
#         "+397100683111",
#         "Trasportatore",
#     ],
#     [
#         16,
#         "Osvaldo",
#         "Gemignani",
#         "osvaldo.gemignani@gmail.com",
#         "+393042491850",
#         "Trasportatore",
#     ],
#     [
#         17,
#         "Ida",
#         "Cristaldi",
#         "ida.cristaldi@gmail.com",
#         "+392184560673",
#         "Magazziniere",
#     ],
#     [
#         18,
#         "Alfio",
#         "Perioli",
#         "alfio.perioli@gmail.com",
#         "+395681707934",
#         "Trasportatore",
#     ],
#     [19, "Nico", "Saccani", "nico.saccani@gmail.com", "+390661481944", "Trasportatore"],
#     [
#         20,
#         "Carlotta",
#         "Ghisalberti",
#         "carlotta.ghisalberti@gmail.com",
#         "+393299534063",
#         "Trasportatore",
#     ],
#     [21, "Paolo", "Conti", "paolo.conti@gmail.com", "+391920678789", "Trasportatore"],
#     [
#         22,
#         "Zenone",
#         "Gioffre",
#         "zenone.gioffre@gmail.com",
#         "+397681975379",
#         "Magazziniere",
#     ],
#     [23, "Ada", "Gioffre", "ada.gioffre@gmail.com", "+395728710165", "Trasportatore"],
#     [24, "Diego", "Grassi", "diego.grassi@gmail.com", "+394246820768", "Trasportatore"],
#     [
#         25,
#         "Tarso",
#         "Ferrando",
#         "tarso.ferrando@gmail.com",
#         "+397508688509",
#         "Trasportatore",
#     ],
#     [
#         26,
#         "Carlo",
#         "Mainardi",
#         "carlo.mainardi@gmail.com",
#         "+394650226170",
#         "Trasportatore",
#     ],
#     [
#         27,
#         "Pierluigi",
#         "Crotta",
#         "pierluigi.crotta@gmail.com",
#         "+398752337960",
#         "Magazziniere",
#     ],
#     [28, "Romolo", "Cento", "romolo.cento@gmail.com", "+398531782204", "Trasportatore"],
#     [
#         29,
#         "Teogene",
#         "Alberi",
#         "teogene.alberi@gmail.com",
#         "+394143040609",
#         "Magazziniere",
#     ],
#     [
#         30,
#         "Omar",
#         "Cianciulli",
#         "omar.cianciulli@gmail.com",
#         "+398027638915",
#         "Magazziniere",
#     ],
#     [
#         31,
#         "Gabriella",
#         "Bocconi",
#         "gabriella.bocconi@gmail.com",
#         "+397965049794",
#         "Magazziniere",
#     ],
#     [
#         32,
#         "Ulrico",
#         "Grassi",
#         "ulrico.grassi@gmail.com",
#         "+391778976582",
#         "Magazziniere",
#     ],
#     [
#         33,
#         "Alessio",
#         "Amoroso",
#         "alessio.amoroso@gmail.com",
#         "+391967448277",
#         "Trasportatore",
#     ],
#     [
#         34,
#         "Fausto",
#         "Perioli",
#         "fausto.perioli@gmail.com",
#         "+393073595276",
#         "Magazziniere",
#     ],
#     [
#         35,
#         "Ida",
#         "Velliscig",
#         "ida.velliscig@gmail.com",
#         "+397513761673",
#         "Magazziniere",
#     ],
#     [
#         36,
#         "Patrizio",
#         "Amoroso",
#         "patrizio.amoroso@gmail.com",
#         "+399415504719",
#         "Magazziniere",
#     ],
#     [
#         37,
#         "Luciano",
#         "Crespi",
#         "luciano.crespi@gmail.com",
#         "+399717441531",
#         "Trasportatore",
#     ],
#     [
#         38,
#         "Iolanda",
#         "Pastorino",
#         "iolanda.pastorino@gmail.com",
#         "+393687938237",
#         "Magazziniere",
#     ],
#     [39, "Ida", "Belli", "ida.belli@gmail.com", "+395199043214", "Trasportatore"],
#     [
#         40,
#         "Clarissa",
#         "Agostino",
#         "clarissa.agostino@gmail.com",
#         "+398053994612",
#         "Magazziniere",
#     ],
#     [
#         41,
#         "Zefiro",
#         "Prosperi",
#         "zefiro.prosperi@gmail.com",
#         "+392408280242",
#         "Trasportatore",
#     ],
#     [
#         42,
#         "Ennio",
#         "Federici",
#         "ennio.federici@gmail.com",
#         "+399909810198",
#         "Magazziniere",
#     ],
#     [
#         43,
#         "Zetico",
#         "Pasqua",
#         "zetico.pasqua@gmail.com",
#         "+397858634148",
#         "Magazziniere",
#     ],
#     [
#         44,
#         "Ennio",
#         "Genovese",
#         "ennio.genovese@gmail.com",
#         "+398042200541",
#         "Trasportatore",
#     ],
#     [
#         45,
#         "Flavio",
#         "Perioli",
#         "flavio.perioli@gmail.com",
#         "+395784971739",
#         "Trasportatore",
#     ],
#     [
#         46,
#         "Antonella",
#         "Cristaldi",
#         "antonella.cristaldi@gmail.com",
#         "+390101740252",
#         "Trasportatore",
#     ],
#     [
#         47,
#         "Rosella",
#         "Bandi",
#         "rosella.bandi@gmail.com",
#         "+399866672991",
#         "Trasportatore",
#     ],
#     [
#         48,
#         "Alfonso",
#         "Fiorenza",
#         "alfonso.fiorenza@gmail.com",
#         "+397248029831",
#         "Magazziniere",
#     ],
#     [49, "Alfio", "Maffei", "alfio.maffei@gmail.com", "+397450896749", "Magazziniere"],
#     [
#         50,
#         "Agnese",
#         "Olcese",
#         "agnese.olcese@gmail.com",
#         "+395848539486",
#         "Magazziniere",
#     ],
#     [
#         51,
#         "Floriana",
#         "Conti",
#         "floriana.conti@gmail.com",
#         "+395834628921",
#         "Trasportatore",
#     ],
#     [52, "Pippo", "Seddio", "pippo.seddio@gmail.com", "+399553921408", "Trasportatore"],
#     [
#         53,
#         "Erica",
#         "Delle Piane",
#         "erica.delle piane@gmail.com",
#         "+396666914143",
#         "Magazziniere",
#     ],
#     [
#         54,
#         "Paride",
#         "Lombardi",
#         "paride.lombardi@gmail.com",
#         "+398318635712",
#         "Magazziniere",
#     ],
#     [55, "Carola", "Marra", "carola.marra@gmail.com", "+399334755512", "Trasportatore"],
#     [
#         56,
#         "Saverio",
#         "Bernardi",
#         "saverio.bernardi@gmail.com",
#         "+397859255258",
#         "Magazziniere",
#     ],
#     [
#         57,
#         "Debora",
#         "Carcangiu",
#         "debora.carcangiu@gmail.com",
#         "+398007847192",
#         "Trasportatore",
#     ],
#     [58, "Loris", "Mazza", "loris.mazza@gmail.com", "+396028167155", "Magazziniere"],
#     [
#         59,
#         "Natale",
#         "Pasqua",
#         "natale.pasqua@gmail.com",
#         "+395311751004",
#         "Magazziniere",
#     ],
#     [
#         60,
#         "Federica",
#         "Franchi",
#         "federica.franchi@gmail.com",
#         "+398904639302",
#         "Trasportatore",
#     ],
#     [
#         61,
#         "Ornella",
#         "Onofri",
#         "ornella.onofri@gmail.com",
#         "+390444710575",
#         "Trasportatore",
#     ],
#     [
#         62,
#         "Sabrina",
#         "Costa",
#         "sabrina.costa@gmail.com",
#         "+398734664751",
#         "Magazziniere",
#     ],
#     [
#         63,
#         "Calogero",
#         "Capurro",
#         "calogero.capurro@gmail.com",
#         "+395270091591",
#         "Magazziniere",
#     ],
#     [
#         64,
#         "Riccardo",
#         "Moroder",
#         "riccardo.moroder@gmail.com",
#         "+396261913687",
#         "Magazziniere",
#     ],
#     [
#         65,
#         "Gaetano",
#         "Mazza",
#         "gaetano.mazza@gmail.com",
#         "+394166491509",
#         "Magazziniere",
#     ],
#     [
#         66,
#         "Tiberio",
#         "Mereu",
#         "tiberio.mereu@gmail.com",
#         "+392638020850",
#         "Trasportatore",
#     ],
#     [
#         67,
#         "Baldassarre",
#         "Giordano",
#         "baldassarre.giordano@gmail.com",
#         "+396320234510",
#         "Magazziniere",
#     ],
#     [
#         68,
#         "Matteo",
#         "Bruzzone",
#         "matteo.bruzzone@gmail.com",
#         "+390013131107",
#         "Magazziniere",
#     ],
#     [69, "Piera", "Angelo", "piera.angelo@gmail.com", "+392427097816", "Trasportatore"],
#     [
#         70,
#         "Carmelo",
#         "Cutolo",
#         "carmelo.cutolo@gmail.com",
#         "+394481271024",
#         "Magazziniere",
#     ],
#     [
#         71,
#         "Evelyn",
#         "Lombardi",
#         "evelyn.lombardi@gmail.com",
#         "+390883387688",
#         "Trasportatore",
#     ],
#     [
#         72,
#         "Cosimo",
#         "Astolfi",
#         "cosimo.astolfi@gmail.com",
#         "+390179975158",
#         "Trasportatore",
#     ],
#     [
#         73,
#         "Francesca",
#         "Capurro",
#         "francesca.capurro@gmail.com",
#         "+394951406669",
#         "Trasportatore",
#     ],
#     [
#         74,
#         "Alice",
#         "Peluffo",
#         "alice.peluffo@gmail.com",
#         "+397665812240",
#         "Magazziniere",
#     ],
#     [
#         75,
#         "Angelica",
#         "Lorenzi",
#         "angelica.lorenzi@gmail.com",
#         "+391599369432",
#         "Magazziniere",
#     ],
#     [
#         76,
#         "Pasquale",
#         "Mancini",
#         "pasquale.mancini@gmail.com",
#         "+398219521966",
#         "Magazziniere",
#     ],
#     [
#         77,
#         "Oliviero",
#         "Longo",
#         "oliviero.longo@gmail.com",
#         "+399917327590",
#         "Trasportatore",
#     ],
#     [
#         78,
#         "Matteo",
#         "Velliscig",
#         "matteo.velliscig@gmail.com" "+393791388939",
#         "Trasportatore",
#     ],
#     [
#         79,
#         "Ultimo",
#         "Crespi",
#         "ultimo.crespi@gmail.com",
#         "+399013031501",
#         "Magazziniere",
#     ],
#     [
#         80,
#         "Paola",
#         "Fiaschi",
#         "paola.fiaschi@gmail.com",
#         "+393697387558",
#         "Trasportatore",
#     ],
#     [
#         81,
#         "Pippo",
#         "Zambarbieri",
#         "pippo.zambarbieri@gmail.com",
#         "+397387116288",
#         "Magazziniere",
#     ],
#     [
#         82,
#         "Riccardo",
#         "Farina",
#         "riccardo.farina@gmail.com",
#         "+398258784061",
#         "Trasportatore",
#     ],
#     [
#         83,
#         "Martino",
#         "Craxi",
#         "martino.craxi@gmail.com",
#         "+392772173507",
#         "Trasportatore",
#     ],
#     [
#         84,
#         "Piera",
#         "Santoro",
#         "piera.santoro@gmail.com",
#         "+392677019991",
#         "Trasportatore",
#     ],
#     [
#         85,
#         "Marcella",
#         "Gottardo",
#         "marcella.gottardo@gmail.com",
#         "+395835579422",
#         "Trasportatore",
#     ],
#     [
#         86,
#         "Valentina",
#         "Carelli",
#         "valentina.carelli@gmail.com",
#         "+397021353385",
#         "Trasportatore",
#     ],
#     [
#         87,
#         "Leandro",
#         "Paduano",
#         "leandro.paduano@gmail.com",
#         "+397283810272",
#         "Magazziniere",
#     ],
#     [88, "Emilio", "Mazza", "emilio.mazza@gmail.com", "+392351663668", "Magazziniere"],
#     [
#         89,
#         "Mattia",
#         "Gelmini",
#         "mattia.gelmini@gmail.com",
#         "+396934869335",
#         "Magazziniere",
#     ],
#     [
#         90,
#         "Riccardo",
#         "Bianchi",
#         "riccardo.bianchi@gmail.com",
#         "+390146524978",
#         "Magazziniere",
#     ],
#     [91, "Isacco", "Fulco", "isacco.fulco@gmail.com", "+397749859932", "Magazziniere"],
#     [
#         92,
#         "Nada",
#         "Bruzzone",
#         "nada.bruzzone@gmail.com",
#         "+395307642635",
#         "Trasportatore",
#     ],
#     [
#         93,
#         "Emilio",
#         "Rinaldi",
#         "emilio.rinaldi@gmail.com",
#         "+397469847737",
#         "Magazziniere",
#     ],
#     [
#         94,
#         "Aurora",
#         "Aspesi",
#         "aurora.aspesi@gmail.com",
#         "+396179917923",
#         "Trasportatore",
#     ],
#     [
#         95,
#         "Osvaldo",
#         "Molinari",
#         "osvaldo.molinari@gmail.com",
#         "+395632149142",
#         "Magazziniere",
#     ],
#     [
#         96,
#         "Viliberto",
#         "Gatti",
#         "viliberto.gatti@gmail.com",
#         "+392378287939",
#         "Trasportatore",
#     ],
#     [
#         97,
#         "Samuele",
#         "Marchi",
#         "samuele.marchi@gmail.com",
#         "+396905207209",
#         "Magazziniere",
#     ],
#     [
#         98,
#         "Casimiro",
#         "Prosperi",
#         "casimiro.prosperi@gmail.com",
#         "+395656306168",
#         "Magazziniere",
#     ],
#     [
#         99,
#         "Virone",
#         "Abulafia",
#         "virone.abulafia@gmail.com",
#         "+398859583711",
#         "Magazziniere",
#     ],
#     [
#         100,
#         "Cosimo",
#         "Brambilla",
#         "cosimo.brambilla@gmail.com",
#         "+398421772132",
#         "Magazziniere",
#     ],
# ]
# i = 0
# for op in ops:
#     op.append(i % 60 + 1)
#     i += 1
# print(ops)
ops = [
    [
        1,
        "Alessandra",
        "Lorenzi",
        "alessandra.lorenzi@gmail.com",
        "+390609577324",
        "Trasportatore",
        1,
    ],
    [
        2,
        "Aurelio",
        "Peano",
        "aurelio.peano@gmail.com",
        "+397008451872",
        "Trasportatore",
        2,
    ],
    [
        3,
        "Silvia",
        "Crotta",
        "silvia.crotta@gmail.com",
        "+393414395310",
        "Magazziniere",
        3,
    ],
    [4, "Lucio", "Testa", "lucio.testa@gmail.com", "+398184532667", "Magazziniere", 4],
    [
        5,
        "Salvatore",
        "Scarpa",
        "salvatore.scarpa@gmail.com",
        "+392261206459",
        "Magazziniere",
        5,
    ],
    [
        6,
        "Renato",
        "Lombardi",
        "renato.lombardi@gmail.com",
        "+391869894377",
        "Trasportatore",
        6,
    ],
    [
        7,
        "Giacomo",
        "Ferrara",
        "giacomo.ferrara@gmail.com",
        "+395810154858",
        "Trasportatore",
        7,
    ],
    [
        8,
        "Serena",
        "Crespi",
        "serena.crespi@gmail.com",
        "+397784711729",
        "Trasportatore",
        8,
    ],
    [
        9,
        "Anna",
        "De Carlo",
        "anna.de carlo@gmail.com",
        "+391451764342",
        "Trasportatore",
        9,
    ],
    [
        10,
        "Patrizia",
        "Scarpa",
        "patrizia.scarpa@gmail.com",
        "+397570368242",
        "Magazziniere",
        10,
    ],
    [
        11,
        "Bastiano",
        "Zen",
        "bastiano.zen@gmail.com",
        "+395333122280",
        "Trasportatore",
        11,
    ],
    [
        12,
        "Bartolomeo",
        "Astolfi",
        "bartolomeo.astolfi@gmail.com",
        "+396808747170",
        "Trasportatore",
        12,
    ],
    [
        13,
        "Piero",
        "Ghisalberti",
        "piero.ghisalberti@gmail.com",
        "+391151068465",
        "Trasportatore",
        13,
    ],
    [
        14,
        "Vincenzo",
        "Russo",
        "vincenzo.russo@gmail.com",
        "+390386049319",
        "Trasportatore",
        14,
    ],
    [
        15,
        "Cesare",
        "Mancini",
        "cesare.mancini@gmail.com",
        "+397100683111",
        "Trasportatore",
        15,
    ],
    [
        16,
        "Osvaldo",
        "Gemignani",
        "osvaldo.gemignani@gmail.com",
        "+393042491850",
        "Trasportatore",
        16,
    ],
    [
        17,
        "Ida",
        "Cristaldi",
        "ida.cristaldi@gmail.com",
        "+392184560673",
        "Magazziniere",
        17,
    ],
    [
        18,
        "Alfio",
        "Perioli",
        "alfio.perioli@gmail.com",
        "+395681707934",
        "Trasportatore",
        18,
    ],
    [
        19,
        "Nico",
        "Saccani",
        "nico.saccani@gmail.com",
        "+390661481944",
        "Trasportatore",
        19,
    ],
    [
        20,
        "Carlotta",
        "Ghisalberti",
        "carlotta.ghisalberti@gmail.com",
        "+393299534063",
        "Trasportatore",
        20,
    ],
    [
        21,
        "Paolo",
        "Conti",
        "paolo.conti@gmail.com",
        "+391920678789",
        "Trasportatore",
        21,
    ],
    [
        22,
        "Zenone",
        "Gioffre",
        "zenone.gioffre@gmail.com",
        "+397681975379",
        "Magazziniere",
        22,
    ],
    [
        23,
        "Ada",
        "Gioffre",
        "ada.gioffre@gmail.com",
        "+395728710165",
        "Trasportatore",
        23,
    ],
    [
        24,
        "Diego",
        "Grassi",
        "diego.grassi@gmail.com",
        "+394246820768",
        "Trasportatore",
        24,
    ],
    [
        25,
        "Tarso",
        "Ferrando",
        "tarso.ferrando@gmail.com",
        "+397508688509",
        "Trasportatore",
        25,
    ],
    [
        26,
        "Carlo",
        "Mainardi",
        "carlo.mainardi@gmail.com",
        "+394650226170",
        "Trasportatore",
        26,
    ],
    [
        27,
        "Pierluigi",
        "Crotta",
        "pierluigi.crotta@gmail.com",
        "+398752337960",
        "Magazziniere",
        27,
    ],
    [
        28,
        "Romolo",
        "Cento",
        "romolo.cento@gmail.com",
        "+398531782204",
        "Trasportatore",
        28,
    ],
    [
        29,
        "Teogene",
        "Alberi",
        "teogene.alberi@gmail.com",
        "+394143040609",
        "Magazziniere",
        29,
    ],
    [
        30,
        "Omar",
        "Cianciulli",
        "omar.cianciulli@gmail.com",
        "+398027638915",
        "Magazziniere",
        30,
    ],
    [
        31,
        "Gabriella",
        "Bocconi",
        "gabriella.bocconi@gmail.com",
        "+397965049794",
        "Magazziniere",
        31,
    ],
    [
        32,
        "Ulrico",
        "Grassi",
        "ulrico.grassi@gmail.com",
        "+391778976582",
        "Magazziniere",
        32,
    ],
    [
        33,
        "Alessio",
        "Amoroso",
        "alessio.amoroso@gmail.com",
        "+391967448277",
        "Trasportatore",
        33,
    ],
    [
        34,
        "Fausto",
        "Perioli",
        "fausto.perioli@gmail.com",
        "+393073595276",
        "Magazziniere",
        34,
    ],
    [
        35,
        "Ida",
        "Velliscig",
        "ida.velliscig@gmail.com",
        "+397513761673",
        "Magazziniere",
        35,
    ],
    [
        36,
        "Patrizio",
        "Amoroso",
        "patrizio.amoroso@gmail.com",
        "+399415504719",
        "Magazziniere",
        36,
    ],
    [
        37,
        "Luciano",
        "Crespi",
        "luciano.crespi@gmail.com",
        "+399717441531",
        "Trasportatore",
        37,
    ],
    [
        38,
        "Iolanda",
        "Pastorino",
        "iolanda.pastorino@gmail.com",
        "+393687938237",
        "Magazziniere",
        38,
    ],
    [39, "Ida", "Belli", "ida.belli@gmail.com", "+395199043214", "Trasportatore", 39],
    [
        40,
        "Clarissa",
        "Agostino",
        "clarissa.agostino@gmail.com",
        "+398053994612",
        "Magazziniere",
        40,
    ],
    [
        41,
        "Zefiro",
        "Prosperi",
        "zefiro.prosperi@gmail.com",
        "+392408280242",
        "Trasportatore",
        41,
    ],
    [
        42,
        "Ennio",
        "Federici",
        "ennio.federici@gmail.com",
        "+399909810198",
        "Magazziniere",
        42,
    ],
    [
        43,
        "Zetico",
        "Pasqua",
        "zetico.pasqua@gmail.com",
        "+397858634148",
        "Magazziniere",
        43,
    ],
    [
        44,
        "Ennio",
        "Genovese",
        "ennio.genovese@gmail.com",
        "+398042200541",
        "Trasportatore",
        44,
    ],
    [
        45,
        "Flavio",
        "Perioli",
        "flavio.perioli@gmail.com",
        "+395784971739",
        "Trasportatore",
        45,
    ],
    [
        46,
        "Antonella",
        "Cristaldi",
        "antonella.cristaldi@gmail.com",
        "+390101740252",
        "Trasportatore",
        46,
    ],
    [
        47,
        "Rosella",
        "Bandi",
        "rosella.bandi@gmail.com",
        "+399866672991",
        "Trasportatore",
        47,
    ],
    [
        48,
        "Alfonso",
        "Fiorenza",
        "alfonso.fiorenza@gmail.com",
        "+397248029831",
        "Magazziniere",
        48,
    ],
    [
        49,
        "Alfio",
        "Maffei",
        "alfio.maffei@gmail.com",
        "+397450896749",
        "Magazziniere",
        49,
    ],
    [
        50,
        "Agnese",
        "Olcese",
        "agnese.olcese@gmail.com",
        "+395848539486",
        "Magazziniere",
        50,
    ],
    [
        51,
        "Floriana",
        "Conti",
        "floriana.conti@gmail.com",
        "+395834628921",
        "Trasportatore",
        51,
    ],
    [
        52,
        "Pippo",
        "Seddio",
        "pippo.seddio@gmail.com",
        "+399553921408",
        "Trasportatore",
        52,
    ],
    [
        53,
        "Erica",
        "Delle Piane",
        "erica.delle piane@gmail.com",
        "+396666914143",
        "Magazziniere",
        53,
    ],
    [
        54,
        "Paride",
        "Lombardi",
        "paride.lombardi@gmail.com",
        "+398318635712",
        "Magazziniere",
        54,
    ],
    [
        55,
        "Carola",
        "Marra",
        "carola.marra@gmail.com",
        "+399334755512",
        "Trasportatore",
        55,
    ],
    [
        56,
        "Saverio",
        "Bernardi",
        "saverio.bernardi@gmail.com",
        "+397859255258",
        "Magazziniere",
        56,
    ],
    [
        57,
        "Debora",
        "Carcangiu",
        "debora.carcangiu@gmail.com",
        "+398007847192",
        "Trasportatore",
        57,
    ],
    [
        58,
        "Loris",
        "Mazza",
        "loris.mazza@gmail.com",
        "+396028167155",
        "Magazziniere",
        58,
    ],
    [
        59,
        "Natale",
        "Pasqua",
        "natale.pasqua@gmail.com",
        "+395311751004",
        "Magazziniere",
        59,
    ],
    [
        60,
        "Federica",
        "Franchi",
        "federica.franchi@gmail.com",
        "+398904639302",
        "Trasportatore",
        60,
    ],
    [
        61,
        "Ornella",
        "Onofri",
        "ornella.onofri@gmail.com",
        "+390444710575",
        "Trasportatore",
        1,
    ],
    [
        62,
        "Sabrina",
        "Costa",
        "sabrina.costa@gmail.com",
        "+398734664751",
        "Magazziniere",
        2,
    ],
    [
        63,
        "Calogero",
        "Capurro",
        "calogero.capurro@gmail.com",
        "+395270091591",
        "Magazziniere",
        3,
    ],
    [
        64,
        "Riccardo",
        "Moroder",
        "riccardo.moroder@gmail.com",
        "+396261913687",
        "Magazziniere",
        4,
    ],
    [
        65,
        "Gaetano",
        "Mazza",
        "gaetano.mazza@gmail.com",
        "+394166491509",
        "Magazziniere",
        5,
    ],
    [
        66,
        "Tiberio",
        "Mereu",
        "tiberio.mereu@gmail.com",
        "+392638020850",
        "Trasportatore",
        6,
    ],
    [
        67,
        "Baldassarre",
        "Giordano",
        "baldassarre.giordano@gmail.com",
        "+396320234510",
        "Magazziniere",
        7,
    ],
    [
        68,
        "Matteo",
        "Bruzzone",
        "matteo.bruzzone@gmail.com",
        "+390013131107",
        "Magazziniere",
        8,
    ],
    [
        69,
        "Piera",
        "Angelo",
        "piera.angelo@gmail.com",
        "+392427097816",
        "Trasportatore",
        9,
    ],
    [
        70,
        "Carmelo",
        "Cutolo",
        "carmelo.cutolo@gmail.com",
        "+394481271024",
        "Magazziniere",
        10,
    ],
    [
        71,
        "Evelyn",
        "Lombardi",
        "evelyn.lombardi@gmail.com",
        "+390883387688",
        "Trasportatore",
        11,
    ],
    [
        72,
        "Cosimo",
        "Astolfi",
        "cosimo.astolfi@gmail.com",
        "+390179975158",
        "Trasportatore",
        12,
    ],
    [
        73,
        "Francesca",
        "Capurro",
        "francesca.capurro@gmail.com",
        "+394951406669",
        "Trasportatore",
        13,
    ],
    [
        74,
        "Alice",
        "Peluffo",
        "alice.peluffo@gmail.com",
        "+397665812240",
        "Magazziniere",
        14,
    ],
    [
        75,
        "Angelica",
        "Lorenzi",
        "angelica.lorenzi@gmail.com",
        "+391599369432",
        "Magazziniere",
        15,
    ],
    [
        76,
        "Pasquale",
        "Mancini",
        "pasquale.mancini@gmail.com",
        "+398219521966",
        "Magazziniere",
        16,
    ],
    [
        77,
        "Oliviero",
        "Longo",
        "oliviero.longo@gmail.com",
        "+399917327590",
        "Trasportatore",
        17,
    ],
    [
        78,
        "Matteo",
        "Velliscig",
        "matteo.velliscig@gmail.com+393791388939",
        "Trasportatore",
        18,
    ],
    [
        79,
        "Ultimo",
        "Crespi",
        "ultimo.crespi@gmail.com",
        "+399013031501",
        "Magazziniere",
        19,
    ],
    [
        80,
        "Paola",
        "Fiaschi",
        "paola.fiaschi@gmail.com",
        "+393697387558",
        "Trasportatore",
        20,
    ],
    [
        81,
        "Pippo",
        "Zambarbieri",
        "pippo.zambarbieri@gmail.com",
        "+397387116288",
        "Magazziniere",
        21,
    ],
    [
        82,
        "Riccardo",
        "Farina",
        "riccardo.farina@gmail.com",
        "+398258784061",
        "Trasportatore",
        22,
    ],
    [
        83,
        "Martino",
        "Craxi",
        "martino.craxi@gmail.com",
        "+392772173507",
        "Trasportatore",
        23,
    ],
    [
        84,
        "Piera",
        "Santoro",
        "piera.santoro@gmail.com",
        "+392677019991",
        "Trasportatore",
        24,
    ],
    [
        85,
        "Marcella",
        "Gottardo",
        "marcella.gottardo@gmail.com",
        "+395835579422",
        "Trasportatore",
        25,
    ],
    [
        86,
        "Valentina",
        "Carelli",
        "valentina.carelli@gmail.com",
        "+397021353385",
        "Trasportatore",
        26,
    ],
    [
        87,
        "Leandro",
        "Paduano",
        "leandro.paduano@gmail.com",
        "+397283810272",
        "Magazziniere",
        27,
    ],
    [
        88,
        "Emilio",
        "Mazza",
        "emilio.mazza@gmail.com",
        "+392351663668",
        "Magazziniere",
        28,
    ],
    [
        89,
        "Mattia",
        "Gelmini",
        "mattia.gelmini@gmail.com",
        "+396934869335",
        "Magazziniere",
        29,
    ],
    [
        90,
        "Riccardo",
        "Bianchi",
        "riccardo.bianchi@gmail.com",
        "+390146524978",
        "Magazziniere",
        30,
    ],
    [
        91,
        "Isacco",
        "Fulco",
        "isacco.fulco@gmail.com",
        "+397749859932",
        "Magazziniere",
        31,
    ],
    [
        92,
        "Nada",
        "Bruzzone",
        "nada.bruzzone@gmail.com",
        "+395307642635",
        "Trasportatore",
        32,
    ],
    [
        93,
        "Emilio",
        "Rinaldi",
        "emilio.rinaldi@gmail.com",
        "+397469847737",
        "Magazziniere",
        33,
    ],
    [
        94,
        "Aurora",
        "Aspesi",
        "aurora.aspesi@gmail.com",
        "+396179917923",
        "Trasportatore",
        34,
    ],
    [
        95,
        "Osvaldo",
        "Molinari",
        "osvaldo.molinari@gmail.com",
        "+395632149142",
        "Magazziniere",
        35,
    ],
    [
        96,
        "Viliberto",
        "Gatti",
        "viliberto.gatti@gmail.com",
        "+392378287939",
        "Trasportatore",
        36,
    ],
    [
        97,
        "Samuele",
        "Marchi",
        "samuele.marchi@gmail.com",
        "+396905207209",
        "Magazziniere",
        37,
    ],
    [
        98,
        "Casimiro",
        "Prosperi",
        "casimiro.prosperi@gmail.com",
        "+395656306168",
        "Magazziniere",
        38,
    ],
    [
        99,
        "Virone",
        "Abulafia",
        "virone.abulafia@gmail.com",
        "+398859583711",
        "Magazziniere",
        39,
    ],
    [
        100,
        "Cosimo",
        "Brambilla",
        "cosimo.brambilla@gmail.com",
        "+398421772132",
        "Magazziniere",
        40,
    ],
]

idTrasportatori = []
for op in ops:
    if op[5] == "Trasportatore":
        idTrasportatori.append(op[0])

# # MEZZI
# # targhe_macchine = [
# #     "AB123CD",
# #     "EF456GH",
# #     "IJ789KL",
# #     "MN012OP",
# #     "QR345ST",
# #     "UV678WX",
# #     "YZ901AB",
# #     "CD234EF",
# #     "GH567IJ",
# #     "KL890MN",
# #     "OP123QR",
# #     "ST456UV",
# #     "WX789YZ",
# #     "AB012CD",
# #     "EF345GH",
# #     "IJ678KL",
# #     "MN901OP",
# #     "QR234ST",
# #     "UV567WX",
# #     "YZ890AB",
# #     "CD123EF",
# #     "GH456IJ",
# #     "KL789MN",
# #     "OP012QR",
# #     "ST345UV",
# #     "WX678YZ",
# #     "AB901CD",
# #     "EF234GH",
# #     "IJ567KL",
# #     "MN890OP",
# #     "QR123ST",
# #     "UV456WX",
# #     "YZ789AB",
# #     "CD012EF",
# #     "GH345IJ",
# #     "KL678MN",
# #     "OP901QR",
# #     "ST234UV",
# #     "WX567YZ",
# #     "AB890CD",
# #     "EF123GH",
# #     "IJ456KL",
# #     "MN789OP",
# #     "QR012ST",
# #     "UV345WX",
# #     "YZ678AB",
# #     "CD901EF",
# #     "GH234IJ",
# #     "KL567MN",
# #     "OP890QR",
# #     "ST123UV",
# #     "WX456YZ",
# #     "AB789CD",
# #     "EF012GH",
# #     "IJ345KL",
# #     "MN678OP",
# #     "QR901ST",
# #     "UV234WX",
# #     "YZ567AB",
# #     "CD890EF",
# #     "GH123IJ",
# #     "KL456MN",
# #     "OP789QR",
# #     "ST012UV",
# #     "WX345YZ",
# #     "AB678CD",
# #     "EF901GH",
# #     "IJ234KL",
# #     "MN567OP",
# #     "QR890ST",
# #     "UV123WX",
# #     "YZ456AB",
# #     "CD789EF",
# #     "GH012IJ",
# #     "KL345MN",
# #     "OP678QR",
# #     "ST901UV",
# #     "WX234YZ",
# #     "AB567CD",
# #     "EF890GH",
# #     "IJ123KL",
# #     "MN456OP",
# #     "QR789ST",
# #     "UV012WX",
# #     "YZ345AB",
# #     "CD678EF",
# #     "GH901IJ",
# #     "KL234MN",
# # ]

# # iT = 0
# # mezzi = []
# # for id in idTrasportatori:
# #     mezzi.append(
# #         [
# #             targhe_macchine[iT],
# #             id,
# #             r.randint(0, 50) * 10.5 + 100,
# #             r.choice(["NULL", ops[iT][6]]),
# #         ]
# #     )
# #     iT += 1
# # print(mezzi)

listaDate = []
for i in range(0, 2500):
    start_date = dt.datetime(
        2020 + r.randint(0, 2),
        r.randint(1, 12),
        r.randint(1, 28),
        r.randint(0, 23),
        r.randint(0, 59),
    )
    start_date = start_date + dt.timedelta(days=r.randint(0, 120))
    listaDate.append([start_date.strftime("%Y-%m-%d %H:%M:%S")])
    for j in range(0, 5):
        current_date = start_date + dt.timedelta(
            days=r.randint(0, 1), hours=r.randint(3, 23), minutes=r.randint(0, 59)
        )
        timestamp = current_date.strftime("%Y-%m-%d %H:%M:%S")
        listaDate[i].append(timestamp)
        start_date = current_date

print(listaDate)

# pacchi
pacchi = []
scelteDim = ["Grande", "Medio", "Piccolo"]
for i in range(0, 2000):
    pacchi.append(
        [
            400 + i + 1,
            r.randint(1, 100),
            listaDate[i][0],
            r.randint(41, 60),
            scelteDim[r.randint(0, 2)],
            r.randint(1, 10) * 0.75,
            r.randint(0, 1),
        ]
    )
# print(pacchi)

# stato_spedizioni
stato_spedizioni = []
statiSped = ["PCR-SO", "SO-CRS", "CRS-CRS", "CRS-SO", "SO-PCR"]
for i in range(0, len(pacchi) - 1):
    sedi = [r.randint(41, 60)]
    sedi.append(sedi[0] - 20)
    sedi.append(sedi[1] - 20)
    sedi.append(pacchi[i][3] - 40)
    sedi.append(pacchi[i][3] - 20)
    sedi.append(pacchi[i][3])
    for j in range(0, 5):
        stato_spedizioni.append(
            [
                400 + i + 1,
                statiSped[j],
                sedi[j],
                sedi[j + 1],
                listaDate[i][j],
                listaDate[i][j + 1],
                idTrasportatori[r.randint(1, len(idTrasportatori) - 1)],
            ]
        )

# # print(stato_spedizioni)


# # supporto
# def encrypt_string(string, shift):
#     encrypted_string = ""
#     for char in string:
#         if char.isalpha():
#             ascii_offset = 65 if char.isupper() else 97
#             encrypted_char = chr((ord(char) - ascii_offset + shift) % 26 + ascii_offset)
#             encrypted_string += encrypted_char
#         else:
#             encrypted_string += char
#     return encrypted_string


customer_phrases = [
    "Ciao, vorrei tracciare il mio pacco.",
    "Ho bisogno di informazioni sulla consegna del mio ordine.",
    "Il mio pacco è in ritardo, posso avere un aggiornamento?",
    "C'è un problema con la mia spedizione, cosa posso fare?",
    "Vorrei modificare l'indirizzo di consegna del mio pacco.",
    "Il mio pacco è danneggiato, come posso procedere?",
    "Ho perso il numero di tracciamento del mio pacco, potete aiutarmi?",
    "Ho bisogno di organizzare un ritiro per un reso.",
    "Vorrei richiedere un rimborso per una spedizione non consegnata.",
    "Posso avere maggiori dettagli sul servizio di consegna express?",
    "Ho bisogno di organizzare una consegna urgente, è possibile?",
    "Non ho ricevuto alcuna conferma di consegna, posso avere un aggiornamento?",
    "La tracciabilità del mio pacco non è aggiornata da giorni, cosa sta succedendo?",
    "Vorrei richiedere un'assicurazione per la mia spedizione.",
    "Mi servono informazioni sulle tariffe di spedizione internazionale.",
    "C'è un errore sull'etichetta di spedizione, come posso correggerlo?",
    "Il mio pacco è stato consegnato a una persona sbagliata, cosa devo fare?",
    "La mia spedizione è stata ritardata a causa di una calamità naturale, come procedere?",
    "Posso programmare una consegna in un orario specifico?",
    "Vorrei richiedere un'opzione di ritiro presso un punto di ritiro vicino a me.",
    "Il mio pacco è stato perso, come posso avviare una reclamazione?",
    "Ho bisogno di assistenza per compilare il modulo di dichiarazione doganale.",
    "Mi servono informazioni sulle tariffe di spedizione.",
    "Ho bisogno di assistenza per rintracciare un pacco smarrito.",
    "Ho ricevuto un avviso di consegna fallita, cosa devo fare?",
    "Quanto tempo ci vuole per una spedizione internazionale?",
    "La mia spedizione è stata segnata come consegnata, ma non ho ricevuto il pacco.",
    "Posso pianificare una consegna in un orario specifico?",
    "Il pacco è stato consegnato a una persona sbagliata, come posso risolvere?",
    "C'è un limite di peso o dimensioni per le spedizioni?",
    "Ho bisogno di un'assicurazione per il mio pacco, è possibile?",
    "Posso ritirare personalmente il mio pacco presso il vostro magazzino?",
    "La mia spedizione è bloccata in dogana, cosa devo fare?",
    "Vorrei richiedere una consegna urgente per il mio pacco.",
    "Ho cambiato idea sul servizio di spedizione, posso modificarlo?",
    "Il mio pacco è stato danneggiato durante il trasporto, come procedere con un reclamo?",
    "Quando posso aspettarmi la consegna del mio pacco?",
    "Ho bisogno di organizzare una consegna a un indirizzo diverso da quello di fatturazione.",
    "Posso richiedere una consegna sabato o domenica?",
    "Vorrei aggiungere un servizio di avviso di consegna per il mio pacco.",
    "Come posso effettuare il pagamento per il servizio di spedizione?",
    "Ho bisogno di informazioni sulle modalità di restituzione e rimborsi.",
    "Ho bisogno di informazioni sul processo di restituzione di un pacco.",
    "Quali sono le modalità di pagamento accettate per il servizio di spedizione?",
    "C'è un servizio di consegna in giornata disponibile?",
    "Il mio pacco è stato erroneamente consegnato a un indirizzo diverso, come posso risolvere?",
    "Ho bisogno di modificare l'orario di consegna previsto per il mio pacco.",
    "Posso tracciare più pacchi contemporaneamente?",
    "Come posso richiedere un'imballaggio speciale per il mio pacco fragile?",
    "Qual è il numero di contatto per l'assistenza clienti?",
    "Ho bisogno di effettuare una richiesta di autorizzazione per un ritiro presso un punto di ritiro.",
    "Il mio pacco è stato smarrito durante il processo di consegna, cosa devo fare?",
    "Posso modificare l'indirizzo di consegna dopo aver effettuato l'ordine?",
    "Vorrei organizzare una consegna su appuntamento per il mio pacco.",
    "Come posso richiedere una copia della fattura per il servizio di spedizione?",
    "Il mio pacco è stato danneggiato a causa di una confezione inadeguata, chi è responsabile?",
    "Ho bisogno di informazioni sulle restrizioni di spedizione per oggetti proibiti o pericolosi.",
    "Posso richiedere una consegna in un paese non incluso nella lista di destinazioni disponibili?",
    "Il mio pacco è stato segnato come consegnato, ma non l'ho ricevuto. Cosa devo fare?",
    "Come posso richiedere una consegna in un edificio con accesso limitato o senza ascensore?",
    "Vorrei organizzare una consegna senza contatto fisico per motivi di sicurezza.",
    "Ho dimenticato di inserire il codice di sconto durante il processo di spedizione, posso aggiungerlo successivamente?",
]

customer_responses = [
    "Certamente, posso aiutarti a tracciare il tuo pacco. Mi serve il numero di tracciamento.",
    "Sì, posso fornirti informazioni sulla consegna del tuo ordine. Per favore, forniscimi il numero di tracciamento.",
    "Mi scuso per il ritardo. Sto verificando lo stato della tua spedizione e ti fornirò un aggiornamento a breve.",
    "Mi dispiace per l'inconveniente. Per favore, descrivimi il problema in dettaglio per poterti aiutare al meglio.",
    "Certamente, posso assisterti nella modifica dell'indirizzo di consegna. Per favore, forniscimi l'indirizzo corretto.",
    "Mi dispiace che il tuo pacco sia danneggiato. Possiamo organizzare un ritiro e avviare una procedura di reso.",
    "Nessun problema. Forniscimi alcuni dettagli sulla spedizione e cercherò il numero di tracciamento per te.",
    "Posso organizzare il ritiro del tuo reso. Per favore, forniscimi i dettagli sulla spedizione di ritorno.",
    "Mi dispiace per l'inconveniente. Possiamo valutare la situazione e procedere con la richiesta di rimborso.",
    "Certamente, il servizio di consegna express offre tempi di consegna più rapidi rispetto al servizio standard.",
    "Sì, possiamo organizzare una consegna in un orario specifico. Per favore, forniscimi le tue preferenze di orario.",
    "Hai la possibilità di selezionare un punto di ritiro vicino a te durante il processo di spedizione.",
    "Mi dispiace che il tuo pacco sia stato perso. Possiamo avviare una procedura di reclamo e cercare una soluzione.",
    "Posso assisterti nella compilazione del modulo di dichiarazione doganale. Fammi sapere cosa hai bisogno di aiuto.",
    "Sì, possiamo organizzare una consegna urgente per te. Per favore, forniscimi i dettagli della spedizione.",
    "Mi scuso per l'inconveniente. Sto verificando la situazione e ti fornirò un aggiornamento il prima possibile.",
    "Mi dispiace per l'inconveniente. Ci stiamo impegnando per risolvere il problema e consegnare il tuo pacco al più presto.",
    "Posso aiutarti ad aggiungere un'assicurazione alla tua spedizione. Fammi sapere il valore dichiarato del pacco.",
    "Certamente, posso fornirti le informazioni sulle tariffe di spedizione internazionale. Qual è la destinazione della spedizione?",
    "Mi dispiace per l'errore sull'etichetta di spedizione. Ti prego di fornirmi i dettagli corretti per procedere con la correzione.",
    "Mi scuso per l'errore. Possiamo avviare un'indagine interna per risolvere il problema con la consegna errata.",
    "Mi dispiace per l'inconveniente causato dalla calamità naturale. Ti prego di fornirmi maggiori dettagli per assisterti nel miglior modo possibile.",
    "Certamente, possiamo programmare la consegna del tuo pacco in un orario specifico. Qual è l'orario di consegna preferito?",
    "Assolutamente, puoi selezionare un punto di ritiro vicino a te durante la procedura di spedizione.",
    "Mi dispiace per la perdita del tuo pacco. Possiamo avviare una procedura di ricerca e fare il possibile per recuperarlo o fornirti un rimborso.",
    "Posso assisterti nella compilazione del modulo di dichiarazione doganale. Fammi sapere quali informazioni sono necessarie.",
    "Mi dispiace per l'inconveniente. Cercheremo di risolvere la situazione nel minor tempo possibile e ti forniremo un aggiornamento.",
    "Sì, possiamo organizzare una consegna urgente per te. Ti prego di fornirmi il dettaglio dell'indirizzo e dell'orario preferito.",
    "Mi dispiace che tu non abbia ricevuto la conferma di consegna. Sto verificando la situazione e ti fornirò un aggiornamento al più presto.",
    "Mi scuso per la mancata aggiornamento sulla tracciabilità del tuo pacco. Sto indagando sul problema e ti terrò informato.",
    "Perfetto, posso assisterti nell'aggiungere un'assicurazione alla tua spedizione. Per favore, forniscimi il valore dichiarato del pacco.",
    "Certamente, posso fornirti le informazioni sulle tariffe di spedizione internazionale. Ti prego di fornirmi la destinazione esatta.",
    "Mi dispiace per l'errore sull'etichetta di spedizione. Ti prego di inviarmi le correzioni necessarie per procedere con la modifica.",
    "Mi scuso per l'inconveniente causato dalla consegna errata. Verificheremo e risolveremo il problema il prima possibile.",
    "Mi dispiace per il ritardo causato dalla calamità naturale. Ti prego di fornirmi ulteriori dettagli per assisterti nel modo migliore.",
    "Certamente, possiamo programmare la consegna del tuo pacco in un orario specifico. Qual è l'orario di consegna preferito per te?",
    "Assolutamente, puoi selezionare un punto di ritiro vicino a te durante la procedura di spedizione.",
    "Mi dispiace per la perdita del tuo pacco. Avvieremo una procedura di ricerca e ti forniremo un aggiornamento al riguardo.",
    "Posso assisterti nella compilazione del modulo di dichiarazione doganale. Fammi sapere quali informazioni sono necessarie.",
    "Mi dispiace per l'inconveniente. Stiamo lavorando per risolvere il problema il prima possibile e ti aggiorneremo sull'esito.",
    "Possiamo organizzare una consegna urgente per te. Ti prego di fornirmi l'indirizzo completo e l'orario di consegna preferito.",
    "Mi scuso per il disagio. Sto verificando lo stato della tua spedizione e ti fornirò un aggiornamento il prima possibile.",
    "Mi dispiace per l'inconveniente. Sto facendo tutto il possibile per risolvere il problema con la tua spedizione.",
    "Posso aiutarti ad aggiungere un'assicurazione alla tua spedizione. Per favore, fammi sapere il valore dichiarato del pacco.",
    "Certamente, posso fornirti informazioni sulle tariffe di spedizione internazionale. Qual è il paese di destinazione?",
    "Mi scuso per l'errore sull'etichetta di spedizione. Per risolvere il problema, ti prego di fornirmi i dettagli corretti.",
    "Mi dispiace per l'errore nella consegna. Sto lavorando per risolvere la situazione e consegnare il tuo pacco correttamente.",
    "Mi dispiace per il ritardo causato dalla calamità naturale. Forniscimi ulteriori dettagli per una migliore assistenza.",
    "Certamente, possiamo programmare la consegna del tuo pacco in un orario specifico. Qual è l'orario di consegna preferito per te?",
    "Puoi selezionare un punto di ritiro vicino a te durante il processo di spedizione per maggiore comodità.",
    "Mi dispiace per la perdita del tuo pacco. Faremo tutto il possibile per risolvere la situazione e fornirti un rimborso, se necessario.",
    "Posso assisterti nella compilazione del modulo di dichiarazione doganale. Fammi sapere quali informazioni sono necessarie.",
    "Mi dispiace per l'inconveniente. Stiamo lavorando per risolvere il problema il prima possibile e ti aggiorneremo sullo stato.",
    "Possiamo organizzare una consegna con firma per garantire che solo tu possa ricevere il pacco. Fammi sapere se desideri attivare questa opzione.",
    "Mi scuso per l'errore nella consegna dell'ordine. Verificheremo cosa è accaduto e ti forniremo una soluzione al più presto.",
    "Mi dispiace per il ritardo nella consegna. Sto controllando lo stato e ti fornirò un aggiornamento dettagliato.",
    "Possiamo organizzare un ritiro del pacco presso il tuo indirizzo. Fammi sapere quando sarebbe il momento migliore per te.",
    "Mi dispiace per il danno al tuo pacco. Possiamo avviare una procedura di reclamo e valutare le opzioni di risarcimento.",
    "Posso fornirti informazioni sui tempi di transito stimati per la tua spedizione. Per favore, forniscimi l'indirizzo di destinazione.",
    "Mi scuso per il disagio. Sto verificando la situazione e ti fornirò un aggiornamento sullo stato della spedizione.",
    "Mi dispiace per l'inconveniente. Verificheremo cosa è successo e faremo tutto il possibile per risolvere il problema.",
]

# supporti = []
# for i in range(0, 100):
#     idC = r.randint(1, 101)
#     idO = r.randint(1, 101)
#     start_date = dt.datetime(
#         2020 + r.randint(0, 2),
#         r.randint(1, 12),
#         r.randint(1, 28),
#         r.randint(0, 23),
#         r.randint(0, 59),
#     )
#     daChi = r.choice([0, 1])
#     if daChi == 0:
#         supporti.append(
#             [
#                 idC,
#                 idO,
#                 start_date.strftime("%Y-%m-%d %H:%M:%S"),
#                 encrypt_string(
#                     customer_phrases[r.randint(0, len(customer_phrases) - 1)],
#                     r.randint(1, 20),
#                 ).replace("'", ""),
#                 daChi,
#             ]
#         )
#     else:
#         supporti.append(
#             [
#                 idC,
#                 idO,
#                 start_date.strftime("%Y-%m-%d %H:%M:%S"),
#                 encrypt_string(
#                     customer_responses[r.randint(0, len(customer_responses) - 1)],
#                     r.randint(1, 20),
#                 ).replace("'", ""),
#                 daChi,
#             ]
#         )
#     nMess = r.randint(0, 20)

#     for j in range(0, nMess):
#         current_date = start_date + dt.timedelta(
#             hours=r.randint(1, 5), minutes=r.randint(0, 59), seconds=r.randint(0, 59)
#         )
#         daChi = r.choice([0, 1])
#         if daChi == 0:
#             supporti.append(
#                 [
#                     idC,
#                     idO,
#                     current_date.strftime("%Y-%m-%d %H:%M:%S"),
#                     encrypt_string(
#                         customer_phrases[r.randint(0, len(customer_phrases) - 1)],
#                         r.randint(1, 20),
#                     ).replace("'", ""),
#                     daChi,
#                 ]
#             )
#         else:
#             supporti.append(
#                 [
#                     idC,
#                     idO,
#                     current_date.strftime("%Y-%m-%d %H:%M:%S"),
#                     encrypt_string(
#                         customer_responses[r.randint(0, len(customer_responses) - 1)],
#                         r.randint(1, 20),
#                     ).replace("'", ""),
#                     daChi,
#                 ]
#             )
#         start_date = current_date
# print(supporti)

# insertsupporto = "INSERT INTO SUPPORTO VALUES\n"

# for supp in supporti:
#     insertsupporto += (
#         "("
#         + str(supp[0])
#         + ", "
#         + str(supp[1])
#         + ", "
#         + "TO_TIMESTAMP('"
#         + str(supp[2])
#         + "', 'YYYY-MM-DD HH24:MI:SS'), '"
#         + str(supp[3])
#         + "', "
#         + str(supp[4])
#         + "),\n"
#     )

# with open("supporto.txt", "w") as file:
#     file.write(insertsupporto)

insertpacchi = "INSERT INTO PACCHI VALUES\n"

for pacco in pacchi:
    insertpacchi += (
        "("
        + str(pacco[0])
        + ", "
        + str(pacco[1])
        + ", "
        + "TO_TIMESTAMP('"
        + str(pacco[2])
        + "', 'YYYY-MM-DD HH24:MI:SS'), "
        + str(pacco[3])
        + ", '"
        + str(pacco[4])
        + "', "
        + str(pacco[5])
        + ", "
        + str(pacco[6])
        + "),\n"
    )

with open("pacchi_aggiunta.txt", "w") as file:
    file.write(insertpacchi)

insertstato = "INSERT INTO STATO_SPEDIZIONI VALUES\n"

for st in stato_spedizioni:
    insertstato += (
        "("
        + str(st[0])
        + ", '"
        + str(st[1])
        + "', "
        + str(st[2])
        + ", "
        + str(st[3])
        + ", "
        + "TO_TIMESTAMP('"
        + str(st[4])
        + "', 'YYYY-MM-DD HH24:MI:SS'), "
        + "TO_TIMESTAMP('"
        + str(st[5])
        + "', 'YYYY-MM-DD HH24:MI:SS'), "
        + str(st[6])
        + "),\n"
    )

with open("stato_spedizioni_aggiunta.txt", "w") as file:
    file.write(insertstato)
